# Generated by Django 4.2 on 2023-11-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceinfield',
            old_name='analyzer_id',
            new_name='analyzer',
        ),
        migrations.RenameField(
            model_name='deviceinfield',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт'), ('in_progress', 'B работе'), ('need_info', 'Требуется информация')], max_length=50, verbose_name='Статус заявки'),
        ),
    ]
