# Generated by Django 4.2 on 2023-11-07 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_rename_analyzer_id_deviceinfield_analyzer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_cuty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_update',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_city',
            field=models.TextField(default=0, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_updated_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее изменение'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.TextField(verbose_name='Наименование организации'),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.TextField(verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.TextField(verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='deviceinfield',
            name='analyzer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders_app.device', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='deviceinfield',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders_app.customer', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='deviceinfield',
            name='owner_status',
            field=models.TextField(verbose_name='Статус принадлежности'),
        ),
        migrations.AlterField(
            model_name='deviceinfield',
            name='serial_number',
            field=models.TextField(verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.TextField(choices=[('open', 'открыта'), ('closed', 'закрыта'), ('in progress', 'в работе'), ('need info', 'нужна информация')], verbose_name='Статус заявки'),
        ),
        migrations.AlterModelTable(
            name='deviceinfield',
            table='devices_in_fields',
        ),
    ]
