# Generated by Django 4.2 on 2023-11-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_remove_customer_customer_cuty_remove_order_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
    ]
