# Generated by Django 4.2 on 2023-11-07 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0004_alter_order_created_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
    ]
